sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

script:
  - >-
    npm install &&
    npm run pretty-ci &&
    npm run test &&
    npm run build:prod &&
    npm prune --production &&
    docker build -t tellios/staticless .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push tellios/staticless;
    fi
